#!/usr/bin/zsh

link="${XDG_CONFIG_HOME}/alacritty/font.yml"

if [[ -L "$link" ]]; then
	target=$(readlink "$link")
	case "$target" in
		*sf-mono.yml)
			ln -sf sgi-screen.yml "$link"
			touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
			;;
		*sgi-screen.yml)
			ln -sf pragmata-pro.yml "$link"
			touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
			;;
		*)
			ln -sf sf-mono.yml "$link"
			touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
			;;
	esac
else
	ln -sf sf-mono.yml "$link"
	touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
fi
