#!/usr/bin/zsh

link="${XDG_CONFIG_HOME}/alacritty/colorscheme.yml"

if [[ -L "$link" ]]; then
	target=$(readlink "$link")
	case "$target" in
		*ysgrifennwr.yml)
			ln -sf fishchips.yml "$link"
			touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
			;;
		*qillqaq.yml)
			ln -sf ysgrifennwr.yml "$link"
			touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
			;;
		*)
			ln -sf qillqaq.yml "$link"
			touch "${XDG_CONFIG_HOME}/alacritty/alacritty.yml"
			;;
	esac
else
	ln -sf qillqaq.yml "$link"
fi
