#!/usr/bin/zsh

case "$1" in
	*.tar.bz2)	tar -xvjf "$1"		;;
	*.tar.gz)	tar -xvzf "$1"		;;
	*.tar.lz)   	tar --lzip -xvf "$1"	;;
	*.tar.xz)	tar -xvJf "$1"		;;
	*.tar.zst)	tar --zstd -xvf "$1"	;;
	*.7z)		7z x "$1"		;;
	*.7z.001)	7z x "$1"		;;
	*.lzma)		unlzma "$1"		;;
	*.rar)		unrar x "$1"		;;
	*.deb)		ar -x "$1"		;;
	*.bz2)		bzip2 -d "$1"		;;
	*.lzh)		lha x "$1"		;;
	*.gz)		gunzip -d --verbose "$1";;
	*.tar)		tar -xvf "$1"		;;
	*.tgz)		tar -xvzf "$1"		;;
	*.tbz2)		tar -xvjf "$1"		;;
	*.txz)		tar -xvJf "$1"		;;
	*.xz)		7z x "$1"		;;
	*.zip)		unzip "$1"		;;
	*.zst)		unzstd "$1"		;;
	*.Z)		uncompress "$1"		;;
	*)		echo "'$1' Error: compression type unknown to $0." ;;
esac
