" Generated by colorsupport.vim (DO NOT MODIFY THIS LINE)
hi clear
if exists("syntax_on")
  syntax reset
endif
hi Normal guibg=#f3f2ed guifg=#404040 gui=none cterm=none ctermfg=238 ctermbg=15
set background=light
let g:colors_name = "neutron"
hi SpecialKey gui=NONE guifg=Blue guibg=NONE cterm=NONE ctermfg=21 ctermbg=NONE
hi NonText gui=bold guifg=Blue guibg=NONE cterm=bold ctermfg=21 ctermbg=NONE
hi Directory gui=NONE guifg=Blue guibg=NONE cterm=NONE ctermfg=21 ctermbg=NONE
hi ErrorMsg gui=NONE guifg=White guibg=Red cterm=NONE ctermfg=231 ctermbg=196
hi IncSearch gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi Search gui=NONE guifg=NONE guibg=Yellow cterm=NONE ctermfg=NONE ctermbg=226
hi MoreMsg gui=bold guifg=SeaGreen guibg=NONE cterm=bold ctermfg=29 ctermbg=NONE
hi ModeMsg gui=bold guifg=NONE guibg=NONE cterm=bold ctermfg=NONE ctermbg=NONE
hi LineNr gui=NONE guifg=Brown guibg=NONE cterm=NONE ctermfg=124 ctermbg=NONE
hi Question gui=bold guifg=SeaGreen guibg=NONE cterm=bold ctermfg=29 ctermbg=NONE
hi StatusLine gui=bold,reverse guifg=NONE guibg=NONE cterm=bold,reverse ctermfg=NONE ctermbg=NONE
hi StatusLineNC gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi VertSplit gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi Title gui=bold guifg=Magenta guibg=NONE cterm=bold ctermfg=201 ctermbg=NONE
hi Visual gui=NONE guifg=NONE guibg=LightGrey cterm=NONE ctermfg=NONE ctermbg=252
hi VisualNOS gui=bold,underline guifg=NONE guibg=NONE cterm=bold,underline ctermfg=NONE ctermbg=NONE
hi WarningMsg gui=NONE guifg=Red guibg=NONE cterm=NONE ctermfg=196 ctermbg=NONE
hi WildMenu gui=NONE guifg=Black guibg=Yellow cterm=NONE ctermfg=16 ctermbg=226
hi Folded gui=NONE guifg=DarkBlue guibg=LightGrey cterm=NONE ctermfg=18 ctermbg=252
hi FoldColumn gui=NONE guifg=DarkBlue guibg=Grey cterm=NONE ctermfg=18 ctermbg=250
hi DiffAdd gui=NONE guifg=NONE guibg=LightBlue cterm=NONE ctermfg=NONE ctermbg=152
hi DiffChange gui=NONE guifg=NONE guibg=LightMagenta cterm=NONE ctermfg=NONE ctermbg=LightMagenta
hi DiffDelete gui=bold guifg=Blue guibg=LightCyan cterm=bold ctermfg=21 ctermbg=195
hi DiffText gui=bold guifg=NONE guibg=Red cterm=bold ctermfg=NONE ctermbg=196
hi SignColumn gui=NONE guifg=DarkBlue guibg=Grey cterm=NONE ctermfg=18 ctermbg=250
hi SpellBad gui=undercurl guifg=NONE guisp=Red cterm=undercurl ctermfg=NONE ctermbg=196
hi SpellCap gui=undercurl guifg=NONE guisp=Blue cterm=undercurl ctermfg=NONE ctermbg=21
hi SpellRare gui=undercurl guifg=NONE guisp=Magenta cterm=undercurl ctermfg=NONE ctermbg=201
hi SpellLocal gui=undercurl guifg=NONE guisp=DarkCyan cterm=undercurl ctermfg=NONE ctermbg=30
hi Pmenu gui=NONE guifg=NONE guibg=LightMagenta cterm=NONE ctermfg=NONE ctermbg=LightMagenta
hi PmenuSel gui=NONE guifg=NONE guibg=Grey cterm=NONE ctermfg=NONE ctermbg=250
hi PmenuSbar gui=NONE guifg=NONE guibg=Grey cterm=NONE ctermfg=NONE ctermbg=250
hi PmenuThumb gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi TabLine gui=underline guifg=NONE guibg=LightGrey cterm=underline ctermfg=NONE ctermbg=252
hi TabLineSel gui=bold guifg=NONE guibg=NONE cterm=bold ctermfg=NONE ctermbg=NONE
hi TabLineFill gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi CursorColumn gui=NONE guifg=NONE guibg=Grey90 cterm=NONE ctermfg=NONE ctermbg=254
hi CursorLine gui=NONE guifg=NONE guibg=Grey90 cterm=NONE ctermfg=NONE ctermbg=254
hi Cursor gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi lCursor gui=reverse guifg=NONE guibg=NONE cterm=reverse ctermfg=NONE ctermbg=NONE
hi MatchParen gui=NONE guifg=NONE guibg=Cyan cterm=NONE ctermfg=NONE ctermbg=51
hi Cursor guibg=#404040 guifg=#a0a0a0 ctermfg=247 ctermbg=238
hi CursorColumn guibg=#e0e0e0 guifg=#202020 ctermfg=234 ctermbg=254
hi CursorLine guibg=#e0e0e0 guifg=#202020 ctermfg=234 ctermbg=254
hi NonText guibg=#d0d0d0 guifg=#606060 gui=none cterm=none ctermfg=59 ctermbg=252
hi Visual guibg=#fffac8 guifg=#404040 gui=none cterm=none ctermfg=238 ctermbg=230
hi Folded guibg=#e8e5d0 guifg=#606060 gui=none cterm=none ctermfg=59 ctermbg=253
hi TabLineFill guibg=#d0d0d0 guifg=#606060 gui=none cterm=none ctermfg=59 ctermbg=252
hi SpecialKey guibg=#e8e8e8 guifg=#a0a0a0 gui=none cterm=none ctermfg=247 ctermbg=254
hi Search guibg=#808080 guifg=#ffffff gui=bold cterm=bold ctermfg=231 ctermbg=244
hi ModeMsg guibg=#f3f2ed guifg=#304050 gui=bold cterm=bold ctermfg=238 ctermbg=15
hi MoreMsg guibg=#f3f2ed guifg=#304050 gui=bold cterm=bold ctermfg=238 ctermbg=15
hi StatusLine guibg=#808080 guifg=#f3f2ed gui=bold cterm=bold ctermfg=15 ctermbg=244
hi StatusLineNC guibg=#707070 guifg=#d0d0d0 gui=none cterm=none ctermfg=252 ctermbg=242
hi VertSplit guibg=#707070 guifg=#909090 gui=none cterm=none ctermfg=246 ctermbg=242
hi LineNr guibg=#dadada guifg=#808080 gui=none cterm=none ctermfg=244 ctermbg=253
hi DiffAdd guibg=#a67429 guifg=#ffcc7f ctermfg=222 ctermbg=136
hi DiffDelete guibg=#a62910 guifg=#ff7f50 ctermfg=209 ctermbg=124
hi DiffChange guibg=#425c78 guifg=#7fbdff ctermfg=111 ctermbg=60
hi DiffText guibg=#4e9a06 guifg=#8ae234 ctermfg=10 ctermbg=2
hi SpellBad gui=undercurl guisp=#f02020 cterm=undercurl ctermbg=9
hi Title guibg=#f3f2ed guifg=#202020 gui=underline cterm=underline ctermfg=234 ctermbg=15
hi Comment guibg=#f3f2ed guifg=#bbbbbb gui=none cterm=none ctermfg=250 ctermbg=15
hi Constant guibg=#f3f2ed guifg=#957301 gui=none cterm=none ctermfg=94 ctermbg=15
hi String guibg=#f3f2ed guifg=#a07060 gui=none cterm=none ctermfg=131 ctermbg=15
hi Character guibg=#f3f2ed guifg=#bb6245 gui=none cterm=none ctermfg=131 ctermbg=15
hi Number guibg=#f3f2ed guifg=#ba7222 gui=none cterm=none ctermfg=130 ctermbg=15
hi Boolean guibg=#f3f2ed guifg=#d4552c gui=none cterm=none ctermfg=166 ctermbg=15
hi Float guibg=#f3f2ed guifg=#e87a00 gui=none cterm=none ctermfg=172 ctermbg=15
hi Identifier guibg=#f3f2ed guifg=#546c48 gui=none cterm=none ctermfg=8 ctermbg=15
hi Function guibg=#f3f2ed guifg=#37bdaa gui=italic ctermfg=73 ctermbg=15
hi Statement guibg=#f3f2ed guifg=#d2346d gui=none cterm=none ctermfg=167 ctermbg=15
hi Conditional guibg=#f3f2ed guifg=#81ac3a gui=none cterm=none ctermfg=107 ctermbg=15
hi Repeat guibg=#f3f2ed guifg=#aab844 gui=none cterm=none ctermfg=143 ctermbg=15
hi Label guibg=#f3f2ed guifg=#969664 gui=underline cterm=underline ctermfg=101 ctermbg=15
hi Operator guibg=#f3f2ed guifg=#a79a39 gui=none cterm=none ctermfg=137 ctermbg=15
hi Keyword guibg=#f3f2ed guifg=#408077 gui=none cterm=none ctermfg=66 ctermbg=15
hi Exception guibg=#f3f2ed guifg=#a03020 gui=none cterm=none ctermfg=130 ctermbg=15
hi PreProc guibg=#f3f2ed guifg=#7d64af gui=none cterm=none ctermfg=97 ctermbg=15
hi Include guibg=#f3f2ed guifg=#c5a2d8 gui=none cterm=none ctermfg=182 ctermbg=15
hi Define guibg=#f3f2ed guifg=#87005f gui=none cterm=none ctermfg=89 ctermbg=15
hi Macro guibg=#f3f2ed guifg=#79519d gui=none cterm=none ctermfg=97 ctermbg=15
hi PreCondit guibg=#f3f2ed guifg=#75698c gui=none cterm=none ctermfg=96 ctermbg=15
hi Type guibg=#f3f2ed guifg=#7d95ad gui=none cterm=none ctermfg=103 ctermbg=15
hi StorageClass guibg=#f3f2ed guifg=#678b5b gui=none cterm=none ctermfg=65 ctermbg=15
hi Structure guibg=#f3f2ed guifg=#5d6da3 gui=none cterm=none ctermfg=61 ctermbg=15
hi Typedef guibg=#f3f2ed guifg=#5080b0 gui=none cterm=none ctermfg=67 ctermbg=15
hi Special guibg=#f3f2ed guifg=#408077 gui=none cterm=none ctermfg=66 ctermbg=15
hi SpecialChar guibg=#f3f2ed guifg=#603020 gui=none cterm=none ctermfg=237 ctermbg=15
hi Tag guibg=#f3f2ed guifg=#a6a679 gui=underline cterm=underline ctermfg=144 ctermbg=15
hi Delimiter guibg=#f3f2ed guifg=#808080 gui=none cterm=none ctermfg=244 ctermbg=15
hi SpecialComment guibg=#f3f2ed guifg=#caacac gui=none cterm=none ctermfg=181 ctermbg=15
hi Debug guibg=#f3f2ed guifg=#908080 gui=none cterm=none ctermfg=102 ctermbg=15
hi Underlined guibg=#f3f2ed guifg=#202020 gui=underline cterm=underline ctermfg=234 ctermbg=15
hi Error guibg=#faf5cd guifg=#c83c28 gui=none cterm=none ctermfg=9 ctermbg=230
hi ToDo guibg=#dadada guifg=#808080 gui=bold cterm=bold ctermfg=244 ctermbg=253
