#!/bin/sh -e

export RUSTFLAGS="-Clink-arg=-Wl,-z,relro,-z,now -C target-feature=-crt-static"
unset CFLAGS

# Install terminfo to right location.
export TERMINFO=$1/usr/share/terminfo
mkdir -p "$TERMINFO"

cargo build --release --verbose
# --no-default-features --features x11
# https://github.com/rust-lang/cargo/issues/5015#issuecomment-597989961
# https://github.com/alacritty/alacritty/pull/3436

mkdir -p $1/usr/bin
install -D -m 0755 target/release/alacritty $1/usr/bin/alacritty

tic -xe alacritty,alacritty-direct extra/alacritty.info

mkdir -p $1/usr/share/man/man1
gzip -11 -c extra/alacritty.man > $1/usr/share/man/man1/alacritty.1.gz

mkdir -p $1/usr/share/zsh/site-functions/
install -Dm 0644 extra/completions/_alacritty $1/usr/share/zsh/site-functions/_alacritty
