-- This file has been generated by notion. Do not edit.
return {
    [1] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                            ["tls"] = 826.0,
                            ["brs"] = 1094.0,
                            ["tl"] = {
                                ["type"] = "WSplitSplit",
                                ["dir"] = "vertical",
                                ["tls"] = 547.0,
                                ["brs"] = 533.0,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["saved_h"] = 1059.0,
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["level"] = 0.0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 27262981.0,
                                                        ["level"] = 0.0,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 822.0,
                                                            ["x"] = 1.0,
                                                            ["y"] = 7.0,
                                                            ["h"] = 512.0,
                                                        },
                                                        ["sizepolicy"] = "full",
                                                        ["checkcode"] = 3.0,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["w"] = 824.0,
                                                    ["x"] = 1.0,
                                                    ["y"] = 20.0,
                                                    ["h"] = 526.0,
                                                },
                                                ["hidden"] = true,
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<4>",
                                            },
                                            [2] = {
                                                ["type"] = "WGroupCW",
                                                ["level"] = 0.0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 29360133.0,
                                                        ["level"] = 0.0,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 824.0,
                                                            ["x"] = 0.0,
                                                            ["y"] = 5.0,
                                                            ["h"] = 516.0,
                                                        },
                                                        ["sizepolicy"] = "full",
                                                        ["checkcode"] = 4.0,
                                                    },
                                                },
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["w"] = 824.0,
                                                    ["x"] = 1.0,
                                                    ["y"] = 20.0,
                                                    ["h"] = 526.0,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<5>",
                                            },
                                        },
                                        ["saved_y"] = 0.0,
                                        ["name"] = "WFrame<1>",
                                        ["mode"] = 1.0,
                                    },
                                },
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["saved_h"] = 552.0,
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["level"] = 0.0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 16777221.0,
                                                        ["level"] = 0.0,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 824.0,
                                                            ["x"] = 0.0,
                                                            ["y"] = 9.0,
                                                            ["h"] = 494.0,
                                                        },
                                                        ["sizepolicy"] = "full",
                                                        ["checkcode"] = 5.0,
                                                    },
                                                },
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["w"] = 824.0,
                                                    ["x"] = 1.0,
                                                    ["y"] = 20.0,
                                                    ["h"] = 512.0,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<3>",
                                            },
                                        },
                                        ["saved_y"] = 528.0,
                                        ["name"] = "Tiling Frame<1>",
                                        ["mode"] = 1.0,
                                    },
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 6292032.0,
                                                    ["level"] = 0.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 1092.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                        ["h"] = 1059.0,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 6.0,
                                                },
                                            },
                                            ["switchto"] = true,
                                            ["geom"] = {
                                                ["w"] = 1092.0,
                                                ["x"] = 1.0,
                                                ["y"] = 20.0,
                                                ["h"] = 1059.0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<1>",
                                        },
                                    },
                                    ["name"] = "WFrame<2>",
                                },
                            },
                        },
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                            ["h"] = 1080.0,
                        },
                        ["sizepolicy"] = "full",
                        ["level"] = 0.0,
                    },
                },
                ["switchto"] = true,
                ["name"] = "WGroupWS<1>",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "HDMI-2",
                },
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["level"] = 1.0,
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
                ["name"] = "*scratchws*",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                        ["name"] = "*scratchpad*",
                        ["sizepolicy"] = "free_glue",
                        ["mode"] = 0.0,
                    },
                },
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["level"] = 1.0,
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
                ["name"] = "*scratchws*<2>",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                        ["name"] = "*scratchpad*<2>",
                        ["sizepolicy"] = "free_glue",
                        ["mode"] = 0.0,
                    },
                },
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["level"] = 1.0,
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
                ["name"] = "*scratchws*<3>",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                        ["name"] = "*scratchpad*<3>",
                        ["sizepolicy"] = "free_glue",
                        ["mode"] = 0.0,
                    },
                },
            },
        },
        ["name"] = "WScreen<1>",
    },
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1200.0,
                },
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                            ["tls"] = 577.0,
                            ["brs"] = 1343.0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["level"] = 0.0,
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 6291461.0,
                                                    ["level"] = 0.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 575.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                        ["h"] = 1179.0,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 1.0,
                                                },
                                            },
                                            ["switchto"] = true,
                                            ["geom"] = {
                                                ["w"] = 575.0,
                                                ["x"] = 1.0,
                                                ["y"] = 20.0,
                                                ["h"] = 1179.0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW",
                                        },
                                    },
                                    ["saved_w"] = 729.0,
                                    ["name"] = "WFrame",
                                    ["saved_x"] = 0.0,
                                    ["mode"] = 1.0,
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitSplit",
                                ["dir"] = "vertical",
                                ["tls"] = 1185.0,
                                ["brs"] = 15.0,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1.0,
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["level"] = 0.0,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 31457294.0,
                                                        ["level"] = 0.0,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 1341.0,
                                                            ["x"] = 0.0,
                                                            ["y"] = 0.0,
                                                            ["h"] = 1164.0,
                                                        },
                                                        ["sizepolicy"] = "full",
                                                        ["checkcode"] = 2.0,
                                                    },
                                                },
                                                ["switchto"] = true,
                                                ["geom"] = {
                                                    ["w"] = 1341.0,
                                                    ["x"] = 1.0,
                                                    ["y"] = 20.0,
                                                    ["h"] = 1164.0,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<6>",
                                            },
                                        },
                                        ["name"] = "Tiling Frame",
                                    },
                                },
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                            },
                        },
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                            ["h"] = 1200.0,
                        },
                        ["sizepolicy"] = "full",
                        ["level"] = 0.0,
                    },
                },
                ["switchto"] = true,
                ["name"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "HDMI-1",
                },
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<2>",
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["dir"] = "horizontal",
                            ["tls"] = 960.0,
                            ["brs"] = 960.0,
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<3>",
                                },
                            },
                            ["br"] = {
                                ["type"] = "WSplitSplit",
                                ["dir"] = "vertical",
                                ["tls"] = 1185.0,
                                ["brs"] = 15.0,
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1.0,
                                        ["managed"] = {
                                        },
                                        ["name"] = "WFrame<4>",
                                    },
                                },
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                            },
                        },
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                            ["h"] = 1200.0,
                        },
                        ["sizepolicy"] = "full",
                        ["level"] = 0.0,
                    },
                },
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1200.0,
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                    [1] = "HDMI-1",
                },
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["level"] = 1.0,
                ["unnumbered"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1200.0,
                },
                ["name"] = "*scratchws*<1>",
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 1120.0,
                            ["y"] = 300.0,
                            ["h"] = 600.0,
                        },
                        ["name"] = "*scratchpad*<1>",
                        ["sizepolicy"] = "free_glue",
                        ["mode"] = 0.0,
                    },
                },
            },
        },
        ["name"] = "WScreen",
    },
}

