-- This file has been generated by notion. Do not edit.
return {
    [1] = "run:lite /home/xha/.config/@notion/",
    [2] = "man:s6-fdholder-store",
    [3] = "run:obsidian",
    [4] = "run:deadbeef",
    [5] = "run:brave",
    [6] = "man:s6-fdholder-delete",
    [7] = "run:code",
}

