#!/bin/sh -e

patch -p1 < scroll.diff
patch -p1 < blink.diff
patch -p1 < no_bright.diff
patch -p1 < clipboard.diff
patch -p1 < netwmicon.diff

# Install terminfo to right location.
export TERMINFO=$1/usr/share/terminfo
mkdir -p "$TERMINFO"

make
make PREFIX=/usr DESTDIR="$1" install
