#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          3
bspc config window_gap            15
bspc config presel_feedback_color "#FFB525"
bspc config focused_border_color  "#27BBBE"

bspc config split_ratio          0.618034
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config status_prefix        ''

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Gimp-2.10 desktop='^8' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^7' follow=on
bspc rule -a URxvt:journalctl desktop='^10'
bspc rule -a TelegramDesktop desktop='^7' follow=on
bspc rule -a Firefox:Browser state=floating
bspc rule -a Firefox:Navigator desktop='^1' follow=on
bspc rule -a strawberry desktop='^4' follow=on
bspc rule -a Steam desktop='^5' follow=on

pgrep -x panel > /dev/null || panel &

(pidof journalctl || urxvtc -name journalctl -e tmux new-session -A -s journalctl "journalctl -b -f -n 1000") &

bspc wm --adopt-orphans