#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^3'
bspc rule -a Chromium desktop='^1'
bspc rule -a URxvt:journalctl desktop='^10'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a Firefox:Browser state=floating

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &

urxvtc -name journalctl -e tmux new-session -A -s journalctl "journalctl -b -f -n 1000" &

