#!/bin/zsh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          3
bspc config window_gap            10
bspc config presel_feedback_color "#FFB525"
bspc config focused_border_color  "#FC9520"

bspc config automatic_scheme     spiral
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config status_prefix        ''

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Gimp-2.10 desktop='^8' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^7' follow=on
bspc rule -a URxvt:journalctl desktop='^10' locked=on
bspc rule -a URxvt:WeeChat desktop='^7' follow=on locked=on
bspc rule -a TelegramDesktop desktop='^7' follow=on
bspc rule -a Firefox:Browser state=floating
bspc rule -a Firefox:Navigator follow=on locked=on
bspc rule -a Firefox:Navigator -o private=on
bspc rule -a strawberry desktop='^4' follow=on
bspc rule -a Steam desktop='^5' follow=on
bspc rule -a 9menu manage=off focus=on
bspc rule -a mpv locked=on private=on
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a URxvt:\* locked=on
bspc rule -a Sxiv state=floating
bspc rule -a Code private=on

bspc desktop '^4' --layout monocle
bspc desktop '^7' --layout monocle
bspc desktop '^10' --layout monocle

pgrep -x panel > /dev/null || panel &

(pidof journalctl || urxvtc -name journalctl -e tmux new-session -A -s journalctl "journalctl -b -f -n 1000") &

bspc wm --adopt-orphans
