#!/usr/bin/env bash

herbstclient silent new_attr bool my_not_first_autostart
herbstclient emit_hook reload

# remove all existing keybindings
herbstclient keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4  # Use the super key as the main modifier

herbstclient keybind $Mod-Control-Shift-q quit
herbstclient keybind $Mod-Shift-r reload
herbstclient keybind $Mod-q close
herbstclient keybind $Mod-Return spawn urxvtcd
herbstclient keybind $Mod-space spawn ~/Software/dotfiles/bin/dmenu_recent
herbstclient keybind $Mod-e spawn pcmanfm
herbstclient keybind $Mod-l spawn slock

# basic movement
# focusing clients
herbstclient keybind $Mod-Left  focus left
herbstclient keybind $Mod-Down  focus down
herbstclient keybind $Mod-Up    focus up
herbstclient keybind $Mod-Right focus right

# moving clients
herbstclient keybind $Mod-Shift-Left  shift left
herbstclient keybind $Mod-Shift-Down  shift down
herbstclient keybind $Mod-Shift-Up    shift up
herbstclient keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
herbstclient keybind $Mod-u       split   bottom  0.5
herbstclient keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
herbstclient keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
herbstclient keybind $Mod-Control-Left    resize left +$resizestep
herbstclient keybind $Mod-Control-Down    resize down +$resizestep
herbstclient keybind $Mod-Control-Up      resize up +$resizestep
herbstclient keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {"www","code","music","read","etc"} )
tag_keys=( {1..9} 0 )

herbstclient rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    herbstclient add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        herbstclient keybind "$Mod-$key" use_index "$i"
        herbstclient keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
herbstclient keybind $Mod-period use_index +1 --skip-visible
herbstclient keybind $Mod-comma  use_index -1 --skip-visible

# layouting
herbstclient set default_frame_layout 3
herbstclient set_layout grid # The above doesn't change the root frame
herbstclient keybind $Mod-r remove
herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
herbstclient keybind $Mod-Shift-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
herbstclient mouseunbind --all
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 zoom
herbstclient mousebind $Mod-Button3 resize

# focus
herbstclient keybind $Mod-BackSpace   cycle_monitor
herbstclient keybind $Mod-Tab         cycle_all +1
herbstclient keybind $Mod-Shift-Tab   cycle_all -1
herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-i jumpto urgent

# theme
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.floating.reset 1
herbstclient set frame_border_width 0
herbstclient set frame_bg_transparent 1
herbstclient set frame_transparent_width 0
herbstclient set frame_gap 0
herbstclient set always_show_frame 0
herbstclient set window_gap 10
herbstclient set frame_padding 0

herbstclient set smart_window_surroundings 0
herbstclient set smart_frame_surroundings 0
herbstclient set mouse_recenter_gap 0
herbstclient set focus_follows_mouse 0
herbstclient set tree_style '╾│ ├└╼─┐'

herbstclient attr theme.tiling.outer_color '#000000'
herbstclient attr theme.floating.outer_color '#000000'
herbstclient attr theme.active.outer_color '#000000'
herbstclient attr theme.active.color '#e1485a'
herbstclient attr theme.normal.color '#f5f5f5'
herbstclient attr theme.urgent.color '#c81a71'
herbstclient attr theme.outer_width 3
herbstclient attr theme.border_width 6

herbstclient pad 0 20

# rules
herbstclient unrule -F
#herbstclient rule class=XTerm tag=3 # move all xterms to tag 3
herbstclient rule focus=on # normally focus new clients
#herbstclient rule focus=off # normally do not focus new clients
# give focus to most common terminals
#herbstclient rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule class="Code" tag="code"
# the following two should be only one command somehow
herbstclient rule class="Zathura" tag="read"
herbstclient rule class="Vlc" pseudotile=on
herbstclient floating "read" on

# unlock, just to be sure
herbstclient unlock

# start floating on all tags
# for i in ${!tag_names[@]} ; do
#     herbstclient floating "${tag_names[$i]}" on
# done

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# herbstclient detect_monitors

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" $monitor &
# done

if herbstclient silent new_attr bool my_not_first_autostart ; then
    tint2 &
    nm-applet &
    volumeicon &
fi
