#!/usr/bin/env bash

herbstclient emit_hook reload

# remove all existing keybindings
herbstclient keyunbind --all

Mod=Mod4   # Use the super key as the main modifier
bar_font="\"IBM Plex Sans:style=Medium,Regular:pixelsize=15:antialias=true:hintstyle=1:lcdfilter=1:rgba=1\""
dmenu_options=" -m 0 -f -i -fn "$bar_font" -nb \"#1E1E1E\" -nf \"#E5E6E6\" -sb \"#005577\" -sf \"#E5E6E6\""

herbstclient keybind $Mod-Shift-q quit
herbstclient keybind $Mod-Shift-r reload
herbstclient keybind $Mod-q close
herbstclient keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback
herbstclient keybind $Mod-space spawn sh -c "dmenu_recent $dmenu_options"

# basic movement
# focusing clients
herbstclient keybind $Mod-Left  focus left
herbstclient keybind $Mod-Down  focus down
herbstclient keybind $Mod-Up    focus up
herbstclient keybind $Mod-Right focus right
herbstclient keybind $Mod-h     focus left
herbstclient keybind $Mod-j     focus down
herbstclient keybind $Mod-k     focus up
herbstclient keybind $Mod-l     focus right

# moving clients
herbstclient keybind $Mod-Shift-Left  shift left
herbstclient keybind $Mod-Shift-Down  shift down
herbstclient keybind $Mod-Shift-Up    shift up
herbstclient keybind $Mod-Shift-Right shift right
herbstclient keybind $Mod-Shift-h     shift left
herbstclient keybind $Mod-Shift-j     shift down
herbstclient keybind $Mod-Shift-k     shift up
herbstclient keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
herbstclient keybind $Mod-u       split   bottom  0.5
herbstclient keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
herbstclient keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
herbstclient keybind $Mod-Control-h       resize left +$resizestep
herbstclient keybind $Mod-Control-j       resize down +$resizestep
herbstclient keybind $Mod-Control-k       resize up +$resizestep
herbstclient keybind $Mod-Control-l       resize right +$resizestep
herbstclient keybind $Mod-Control-Left    resize left +$resizestep
herbstclient keybind $Mod-Control-Down    resize down +$resizestep
herbstclient keybind $Mod-Control-Up      resize up +$resizestep
herbstclient keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

herbstclient rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    herbstclient add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        herbstclient keybind "$Mod-$key" use_index "$i"
        herbstclient keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
herbstclient keybind $Mod-period use_index +1 --skip-visible
herbstclient keybind $Mod-comma  use_index -1 --skip-visible

# layouting
herbstclient keybind $Mod-r remove
herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
herbstclient keybind $Mod-t                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
herbstclient mouseunbind --all
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 zoom
herbstclient mousebind $Mod-Button3 resize

# focus
herbstclient keybind $Mod-BackSpace   cycle_monitor
herbstclient keybind $Mod-Tab         cycle_all +1
herbstclient keybind $Mod-Shift-Tab   cycle_all -1
herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-i jumpto urgent

# theme
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.floating.reset 1
herbstclient set frame_border_active_color '#222222'
herbstclient set frame_border_normal_color '#101010'
herbstclient set frame_bg_normal_color '#565656'
herbstclient set frame_bg_active_color '#345F0C'
herbstclient set frame_border_width 1
herbstclient set always_show_frame 1
herbstclient set frame_bg_transparent 1
herbstclient set frame_transparent_width 5
herbstclient set frame_gap 4

herbstclient attr theme.active.color '#005577'
herbstclient attr theme.normal.color '#454545'
herbstclient attr theme.urgent.color orange
herbstclient attr theme.inner_width 1
herbstclient attr theme.inner_color black
herbstclient attr theme.border_width 3
herbstclient attr theme.floating.border_width 4
herbstclient attr theme.floating.outer_width 1
herbstclient attr theme.floating.outer_color black
herbstclient attr theme.active.inner_color '#3E4A00'
herbstclient attr theme.active.outer_color '#005577'
herbstclient attr theme.background_color '#1e1e1e'

herbstclient set window_gap 0
herbstclient set frame_padding 0
herbstclient set smart_window_surroundings 0
herbstclient set smart_frame_surroundings 1
herbstclient set mouse_recenter_gap 0
herbstclient set focus_follows_mouse 1

herbstclient keybind $Mod+KP_Insert spawn sh -c 'ponymix mute && ponymix is-muted && dunstify -t 200 "mute" || dunstify -t 200 "volume: "`ponymix get-volume`" %"'
herbstclient keybind $Mod+KP_Add spawn sh -c 'ponymix unmute && ponymix increase 5 && ponymix is-muted && dunstify -t 200 "mute" || dunstify -t 200 "volume: "`ponymix get-volume`" %"'
herbstclient keybind $Mod+KP_Subtract spawn sh -c 'ponymix unmute && ponymix decrease 5 && ponymix is-muted && dunstify -t 200 "mute" || dunstify -t 200 "volume: "`ponymix get-volume`" %"'
herbstclient keybind XF86AudioMute spawn sh -c 'ponymix mute && ponymix is-muted && dunstify -t 200 "mute" || dunstify -t 200 "volume: "`ponymix get-volume`" %"'
herbstclient keybind XF86AudioRaiseVolume spawn sh -c 'ponymix unmute && ponymix increase 5 && ponymix is-muted && dunstify -t 200 "mute" || dunstify -t 200 "volume: "`ponymix get-volume`" %"'
herbstclient keybind XF86AudioLowerVolume spawn sh -c 'ponymix unmute && ponymix decrease 5 && ponymix is-muted && dunstify -t 200 "mute" || dunstify -t 200 "volume: "`ponymix get-volume`" %"'
herbstclient keybind $Mod+KP_End spawn mpc toggle
herbstclient keybind XF86AudioPlay spawn mpc toggle
herbstclient keybind $Mod+KP_Multiply spawn mpc next
herbstclient keybind XF86AudioNext spawn mpc next
herbstclient keybind $Mod+KP_Divide spawn mpc prev
herbstclient keybind XF86AudioPrev spawn mpc prev

herbstclient keybind $Mod+Insert spawn sh -c "clipmenu $dmenu_options"
herbstclient keybind $Mod+Home spawn sh -c "clipmenu-url"
herbstclient keybind $Mod+Shift+m spawn sh -c "simple_mount.sh $dmenu_options"

# rules
herbstclient unrule -F
#herbstclient rule class=XTerm tag=3 # move all xterms to tag 3
herbstclient rule focus=on # normally focus new clients
#herbstclient rule focus=off # normally do not focus new clients
# give focus to most common terminals
#herbstclient rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

herbstclient set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
herbstclient unlock

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# herbstclient detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
