# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options = [ "subvol=@root" "compress-force=zstd:6" "noatime" ];
  };

  boot.initrd.luks.devices."luks-beec750d-bc17-4e53-8b07-94685dc61102" = {
    device = "/dev/disk/by-uuid/beec750d-bc17-4e53-8b07-94685dc61102";
    allowDiscards = true;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress-force=zstd:6" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress-force=zstd:6" "noatime" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options = [ "subvol=@persist" "compress-force=zstd:6" "noatime" ];
  };

  fileSystems."/private" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options = [ "subvol=@private" "compress-force=zstd:6" "noatime" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress-force=zstd:6" "noatime" ];
    neededForBoot = true;
  };

  fileSystems."/var/lib/iwd" = {
    device = "/dev/disk/by-uuid/98f056d6-9b23-4b3f-95ca-45ad63f9d434";
    fsType = "btrfs";
    options =
      [ "subvol=@private/@var-lib-iwd" "compress-force=zstd:6" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7A2A-D02C";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # services.fstrim.enable = true;

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
