#!/bin/sh -e

CFLAGS="$CFLAGS -ffat-lto-objects"
LDFLAGS="$LDFLAGS -flto -ffat-lto-objects"

./configure \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --prefix=/usr \
    --enable-shared \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-openssl \
    --enable-libass \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-libdrm \
    --x86asmexe=nasm \
    --disable-debug \
    \
    --enable-libfdk-aac \
    --enable-libdav1d \
    --enable-libfribidi \
    --enable-libfreetype \
    --enable-vaapi \
    --enable-lto \
    --enable-pic \
    --extra-cflags="$CFLAGS" \
	--optflags="$CFLAGS" \
    --enable-hardcoded-tables

make
make DESTDIR="$1" install install-man

rm -rf "$1/usr/share/ffmpeg/examples"
