import XMonad
import XMonad.Hooks.DynamicLog
import XMonad.Util.EZConfig (additionalKeys)
import XMonad.Util.Run (hPutStrLn, safeSpawn, spawnPipe, unsafeSpawn)
import XMonad.Util.Replace

myConfig =
  def
    { modMask = mod4Mask,
      terminal = "urxvtc",
      focusedBorderColor = "#affe69",
      borderWidth = 2
    }
    `additionalKeys` myKeys -- `removeKeys` [(mod4Mask, xK_q)]

-- override some of the default keybindings and add my own
myKeys =
  [ ((0, 0x1008FF11), unsafeSpawn "pamixer --get-mute && pamixer -u || pamixer -d 2"),
    ((0, 0x1008FF13), unsafeSpawn "pamixer --get-mute && pamixer -u || pamixer -i 2"),
    ((mod4Mask .|. shiftMask, xK_o ), restart "/home/xha/tmp/dwmonad" True)
  ]

--((mod4Mask .|. shiftMask, xK_w), spawn "feh --bg-fill --randomize /home/alinea/Files/wallpaper/*"), -- change wallpaper
--((mod4Mask .|. shiftMask, xK_q), kill), -- close window with mod-shift-Q (default is mod-shift-C)
--((mod4Mask .|. shiftMask, xK_e), io (exitWith ExitSuccess)), -- close xmonad with mod-shift-E (default is mod-shift-Q)
--((mod4Mask .|. shiftMask, xK_r), spawn "if type xmonad; then xmonad --recompile && xmonad --restart; else xmessage xmonad not in \\$PATH: \"$PATH\"; fi"), -- %! Recompile and restart xmonad
--((mod4Mask, xK_x), spawn "scrot '%Y-%m-%d-%H%M%S.png' -b -u -e 'mv $f ~/Files/screenshots/'"), -- take a screenshot of the currently active window
--((mod4Mask .|. shiftMask, xK_x), spawn "scrot '%Y-%m-%d-%H%M%S-full.png' -b -e 'mv $f ~/Files/screenshots/'") -- take a screenshot (of everything)

toggleGapsKey XConfig {XMonad.modMask = mod4Mask} = (mod4Mask, xK_b)

-- configuration of the status bar output generated by xmonad
myPP =
  xmobarPP
    { ppCurrent = xmobarColor "#181715" "#58C5F1" . wrap "[" "]",
      ppTitle = xmobarColor "#14FF08" "",
      ppVisible = xmobarColor "#58C5F1" "#181715" . wrap "(" ")",
      ppUrgent = xmobarColor "#181715" "#D81816",
      ppHidden = xmobarColor "#58C5F1" "#181715",
      ppSep = " — "
    }

main = do
  replace
  xmonad $ myConfig

-- [TODO]
-- Gridselect
-- MasterWidth mit Maus ändern
-- Technical Debt: qualified imports
-- xmobar config importieren
-- safeSpawn
-- Layout-Logos
-- alte Bar-Funktionalität
-- tabbed/sticky Windows
-- Workspaces as Tags
-- Backdrops
-- check fonts: https://github.com/qntm/base65536
-- clipmenu
-- tweak nnn
-- configure `less` https://leahneukirchen.org/blog/archive/2015/02/six-hacks-for-less-1.html
-- Xmonad in /nix/store https://github.com/xmonad/xmonad/issues/61
-- sent
-- urxvt window titles
-- mount /private somewhere else
-- custom "sent" package

