#! /bin/sh

sxhkd &

bspc monitor -d main work chat music logs

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'discord' desktop='^3'
bspc rule -a 'Chromium' desktop='^1'
bspc rule -a 'URxvt:journalctl' desktop='^5'
bspc rule -a '*:zathura' state=tiled
bspc rule -a 'TelegramDesktop' desktop='^3'

bspc wm --adopt-orphans