#! /bin/sh

urxvt256c-mld -q -o -f
sxhkd &

bspc monitor -d main work chat music logs

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'discord' desktop='^3'
bspc rule -a 'Chromium' desktop='^1'
bspc rule -a 'URxvt:journalctl' desktop='^5'
bspc rule -a '*:zathura' state=tiled
bspc rule -a 'TelegramDesktop' desktop='^3'

# wid=$(xdo id -m -a "jigglyroom")
# xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

bspc wm --adopt-orphans
