-- This file has been generated by notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "menu.mainmenu:session/save",
    [3] = "run:obsidian",
    [4] = "run:spotify",
    [5] = "man:youtube-dl",
    [6] = "run:code",
    [7] = "run:brave",
    [8] = "run:lite /home/xha/.config/",
    [9] = "man:SSL_CTX_sess_get_remove_cb",
    [10] = "man:y0",
    [11] = "man:notion",
    [12] = "windowname:cfg_bindings.lua* - lite",
    [13] = "windowname:[SOWM] Roses & Despair : unixporn - Brave",
    [14] = "run:mupdf /home/xha/Downloads/Pavel\092 Tsatsouline\092 -\092 The\092 Quick\092 and\092 the\092 Dead\092 Total\092 Training\092 for\092 the\092 Advanced\092 Minimalis-StrongFirst,\092 Inc.\092 \092(2019\092).epub",
    [15] = "run:mudpf",
    [16] = "run:mupdf",
    [17] = "menu.mainmenu:about-notion",
    [18] = "yesno:y",
    [19] = "menu.mainmenu:styles/look_brownsteel",
    [20] = "run:deadbeef",
}

