-- This file has been generated by notion. Do not edit.
return {
    ["exec"] = {
        ["notionstatus"] = {
            ["retry_delay"] = 60000,
            ["program"] = "go run /home/xha/bin/notionstatus.go",
        },
    },
}

