#!/usr/bin/zsh

resizestep=0.02
accentcolors=("$QI_G" "$QI_M" "$QI_C" "$QI_Y" "$QI_B")
accentcolor="$accentcolors[RANDOM % $#accentcolors + 1]"
mutecmd=(and 🥨 spawn $SHELL -c "pactl set-sink-mute \$(pacmd list-sinks|awk '/\\* index:/{ print \$3 }') true" 🥨 spawn notify-send '🔇 muted')
lowervolumecmd=(and 🥨 spawn $SHELL -c "sink=\$(pacmd list-sinks | awk '/\\* index:/{ print \$3 }'); pactl set-sink-mute \$(pacmd list-sinks|awk '/\\* index:/{ print \$3 }') false; pactl set-sink-volume \"\$sink\" \"\$(( \$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: front/{gsub(\"%\",\"\",\$5); print \$5 }') - 5 ))%\"" 🥨 spawn $SHELL -c "notify-send \"🔉 \$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: front/{gsub(\"%\",\"\",\$5); print \$5 }')%\"" )
raisevolumecmd=(and 🥨 spawn $SHELL -c "sink=\$(pacmd list-sinks | awk '/\\* index:/{ print \$3 }'); pactl set-sink-mute \$(pacmd list-sinks|awk '/\\* index:/{ print \$3 }') false; newvol=\$(( \$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: front/{gsub(\"%\",\"\",\$5); print \$5 }') + 5 )); pactl set-sink-volume \"\$sink\" \"\$(( (\$newvol > 100) ? 100 : \$newvol ))%\"" 🥨 spawn $SHELL -c "notify-send \"🔊 \$(pacmd list-sinks | grep -A 15 '* index' | awk '/volume: front/{gsub(\"%\",\"\",\$5); print \$5 }')%\"" )
strawberryplaycmd=(strawberry --play-pause)
strawberrynextcmd=(strawberry --next)
strawberryprevcmd=(strawberry --restart-or-previous)
backdropcmd=(spawn $SHELL -c "xsetroot -bitmap $HOME/.local/share/backdrops/\`\\ls $HOME/.local/share/backdrops | shuf -n 1 | tr -d '\\n' | tee -a /tmp/wallpaper\` \`printf -- \" -fg #%06x -bg #%06x\\n\" \$(shuf -i0-16777215 -n2) | tee -a /tmp/wallpaper\`")

if [[ $HOST = andermatt ]] ; then;
	maxbrightness=$(</sys/class/backlight/intel_backlight/max_brightness)
	localbinds=(🍂 or 🔙 silent get_attr my_touchpad_enabled 🔙 new_attr bool my_touchpad_enabled \
	🍂 set_attr my_touchpad_enabled true \
	🍂 keybind XF86TouchpadToggle or 🔙 and 🥨 compare my_touchpad_enabled = true 🥨 spawn xinput disable 'AlpsPS/2 ALPS GlidePoint' 🥨 set_attr my_touchpad_enabled false 🔙 and 🥨 spawn xinput enable 'AlpsPS/2 ALPS GlidePoint' 🥨 set_attr my_touchpad_enabled true \
	🍂 keybind XF86MonBrightnessDown and 🥨 spawn $SHELL -c "brightness=\$(</sys/class/backlight/intel_backlight/brightness); new_brightness=\$((-$maxbrightness/10+\$brightness)); actual_brightness=\$((\$new_brightness > 0 ? \$new_brightness : 0)); echo \$actual_brightness > /sys/class/backlight/intel_backlight/brightness" 🥨 spawn $SHELL -c "notify-send \"🔅 \$(( \$(</sys/class/backlight/intel_backlight/brightness) * 100 / $maxbrightness ))%\"" \
	🍂 keybind XF86MonBrightnessUp and 🥨 spawn $SHELL -c "brightness=\$(</sys/class/backlight/intel_backlight/brightness) ; new_brightness=\$(($maxbrightness/10+\$brightness)) ; actual_brightness=\$((\$new_brightness < $maxbrightness ? \$new_brightness : $maxbrightness)) ; echo \$actual_brightness > /sys/class/backlight/intel_backlight/brightness" 🥨 spawn $SHELL -c "notify-send \"🔆 \$(( \$(</sys/class/backlight/intel_backlight/brightness) * 100 / $maxbrightness ))%\"" \
	🍂 keybind XF86AudioMute $mutecmd \
	🍂 keybind XF86AudioLowerVolume $lowervolumecmd \
	🍂 keybind XF86AudioRaiseVolume $raisevolumecmd \
	🍂 keybind XF86AudioPlay spawn $strawberryplaycmd \
	🍂 keybind XF86AudioNext spawn $strawberrynextcmd \
	🍂 keybind XF86AudioPrev spawn $strawberryprevcmd)
fi

herbstclient chain \
🍂 emit_hook reload \
🍂 keyunbind --all \
🍂 mouseunbind --all \
🍂 unrule --all \
🍂 and 🥨 new_attr color my_🦎 🥨 set_attr color my_🦎 `printf -- "#%06x" $(shuf -i0-16777215 -n1)` \
\
🍂 set frame_gap 5 \
🍂 set frame_padding 0 \
🍂 set window_gap 0 \
🍂 set snap_distance 10 \
🍂 set snap_gap 0 \
🍂 set mouse_recenter_gap 0 \
🍂 set frame_border_active_color "$QI_W" \
🍂 set frame_border_normal_color "$QI_W" \
🍂 set frame_border_inner_color "$QI_W" \
🍂 set frame_bg_active_color "$accentcolor" \
🍂 set emit_hook 🖌️ \
🍂 set frame_bg_normal_color "$QI_B_W" \
🍂 set frame_bg_transparent 1 \
🍂 set frame_transparent_width 5 \
🍂 set frame_border_width 1 \
🍂 set frame_border_inner_width 0 \
🍂 set focus_crosses_monitor_boundaries 1 \
🍂 set raise_on_focus 0 \
🍂 set raise_on_focus_temporarily 0 \
🍂 set raise_on_click 1 \
🍂 set window_border_width 4 \
🍂 set window_border_inner_width 1 \
🍂 set window_border_active_color "$accentcolor" \
🍂 set window_border_normal_color "$QI_B_W" \
🍂 set window_border_urgent_color "$QI_R" \
🍂 set window_border_inner_color "$QI_W" \
🍂 set always_show_frame 0 \
🍂 set frame_normal_opacity 100 \
🍂 set frame_active_opacity 100 \
🍂 set default_frame_layout 2 \
🍂 set default_direction_external_only 0 \
🍂 set gapless_grid 1 \
🍂 set smart_frame_surroundings 0 \
🍂 set smart_window_surroundings 0 \
🍂 set focus_follows_mouse 0 \
🍂 set focus_stealing_prevention 0 \
🍂 set swap_monitors_to_get_tag 1 \
🍂 set auto_detect_monitors 0 \
🍂 set tree_style '├│ ├└──┬' \
🍂 set update_dragged_clients 1 \
\
🍂 keybind Mod4+Left  focus left \
🍂 keybind Mod4+Down  focus down \
🍂 keybind Mod4+Up    focus up \
🍂 keybind Mod4+Right focus right \
🍂 keybind Mod4+h     focus left \
🍂 keybind Mod4+j     focus down \
🍂 keybind Mod4+k     focus up \
🍂 keybind Mod4+l     focus right \
🍂 keybind Mod4-Shift-Left or / shift left / chain , lock , shift_to_monitor -l , focus_monitor -l , unlock \
🍂 keybind Mod4-Shift-Down or / shift down / chain , lock , shift_to_monitor -d , focus_monitor -d , unlock \
🍂 keybind Mod4-Shift-Up or / shift up / chain , lock , shift_to_monitor -u , focus_monitor -u , unlock \
🍂 keybind Mod4-Shift-Right or / shift right / chain , lock , shift_to_monitor -r , focus_monitor -r , unlock \
🍂 keybind Mod4-Shift-h or / shift left / chain , lock , shift_to_monitor -l , focus_monitor -l , unlock \
🍂 keybind Mod4-Shift-j or / shift down / chain , lock , shift_to_monitor -d , focus_monitor -d , unlock \
🍂 keybind Mod4-Shift-k or / shift up / chain , lock , shift_to_monitor -u , focus_monitor -u , unlock \
🍂 keybind Mod4-Shift-l or / shift right / chain , lock , shift_to_monitor -r , focus_monitor -r , unlock \
🍂 keybind Mod4+backslash split right 0.6180339887498949 \
🍂 keybind Mod4+minus split bottom 0.6180339887498949 \
🍂 keybind Mod4+x split explode \
🍂 keybind Mod4+Control+h       resize left +$resizestep \
🍂 keybind Mod4+Control+j       resize down +$resizestep \
🍂 keybind Mod4+Control+k       resize up +$resizestep \
🍂 keybind Mod4+Control+l       resize right +$resizestep \
🍂 keybind Mod4+Control+Left    resize left +$resizestep \
🍂 keybind Mod4+Control+Down    resize down +$resizestep \
🍂 keybind Mod4+Control+Up      resize up +$resizestep \
🍂 keybind Mod4+Control+Right   resize right +$resizestep \
\
🍂 silent rename default '!' \
🍂 add '@' \
🍂 add '#' \
🍂 add '$' \
🍂 add '%' \
🍂 add '^' \
🍂 load '!' '(clients grid:0)' \
🍂 load '@' '(split horizontal:0.626100:0 (clients max:1) (split vertical:0.395300:1 (clients max:0) (clients max:0)))' \
🍂 load '#' '(clients grid:0)' \
🍂 load '%' '(split horizontal:0.550000:0 (clients max:0) (clients max:0))' \
🍂 keybind Mod4+1 use_index 0 \
🍂 keybind Mod4+2 use_index 1 \
🍂 keybind Mod4+3 use_index 2 \
🍂 keybind Mod4+4 use_index 3 \
🍂 keybind Mod4+5 use_index 4 \
🍂 keybind Mod4+6 use_index 5 \
🍂 keybind Mod4+Shift+1 move_index 0 \
🍂 keybind Mod4+Shift+2 move_index 1 \
🍂 keybind Mod4+Shift+3 move_index 2 \
🍂 keybind Mod4+Shift+4 move_index 3 \
🍂 keybind Mod4+Shift+5 move_index 4 \
🍂 keybind Mod4+Shift+6 move_index 5 \
🍂 keybind Mod4+Mod1+1 substitute 🔜 tags.focus.name chain ⛓️ lock ⛓️ use_index 0 ⛓️ move 🔜 ⛓️ use 🔜 ⛓️ unlock \
🍂 keybind Mod4+Mod1+2 substitute 🔜 tags.focus.name chain ⛓️ lock ⛓️ use_index 1 ⛓️ move 🔜 ⛓️ use 🔜 ⛓️ unlock \
🍂 keybind Mod4+Mod1+3 substitute 🔜 tags.focus.name chain ⛓️ lock ⛓️ use_index 2 ⛓️ move 🔜 ⛓️ use 🔜 ⛓️ unlock \
🍂 keybind Mod4+Mod1+4 substitute 🔜 tags.focus.name chain ⛓️ lock ⛓️ use_index 3 ⛓️ move 🔜 ⛓️ use 🔜 ⛓️ unlock \
🍂 keybind Mod4+Mod1+5 substitute 🔜 tags.focus.name chain ⛓️ lock ⛓️ use_index 4 ⛓️ move 🔜 ⛓️ use 🔜 ⛓️ unlock \
🍂 keybind Mod4+Mod1+6 substitute 🔜 tags.focus.name chain ⛓️ lock ⛓️ use_index 5 ⛓️ move 🔜 ⛓️ use 🔜 ⛓️ unlock \
🍂 keybind Mod4+7 or 🙈 substitute 🆔 my_7️⃣ or 💀 bring 🆔 💀 substitute 🆕 clients.focus.winid set_attr my_7️⃣ 🆕 🙈 chain ⛓️ new_attr string my_7️⃣ ⛓️ substitute 🆕 clients.focus.winid set_attr my_7️⃣ 🆕 \
🍂 keybind Mod4+8 or 🙈 substitute 🆔 my_8️⃣ or 💀 bring 🆔 💀 substitute 🆕 clients.focus.winid set_attr my_8️⃣ 🆕 🙈 chain ⛓️ new_attr string my_8️⃣ ⛓️ substitute 🆕 clients.focus.winid set_attr my_8️⃣ 🆕 \
🍂 keybind Mod4+9 or 🙈 substitute 🆔 my_9️⃣ or 💀 bring 🆔 💀 substitute 🆕 clients.focus.winid set_attr my_9️⃣ 🆕 🙈 chain ⛓️ new_attr string my_9️⃣ ⛓️ substitute 🆕 clients.focus.winid set_attr my_9️⃣ 🆕 \
🍂 keybind Mod4+Mod1+8 substitute 🆔 my_8️⃣ jumpto 🆔 \
🍂 keybind Mod4+Mod1+7 substitute 🆔 my_7️⃣ jumpto 🆔 \
🍂 keybind Mod4+Mod1+9 substitute 🆔 my_9️⃣ jumpto 🆔 \
🍂 keybind Mod4+Control+Shift+7 substitute 🆔 my_7️⃣ close 🆔 \
🍂 keybind Mod4+Control+Shift+8 substitute 🆔 my_8️⃣ close 🆔 \
🍂 keybind Mod4+Control+Shift+9 substitute 🆔 my_9️⃣ close 🆔 \
🍂 keybind Mod4+Shift+7 chain ⛓️ new_attr string my_7️⃣ ⛓️ substitute 🆕 clients.focus.winid set_attr my_7️⃣ 🆕 \
🍂 keybind Mod4+Shift+8 chain ⛓️ new_attr string my_8️⃣ ⛓️ substitute 🆕 clients.focus.winid set_attr my_8️⃣ 🆕 \
🍂 keybind Mod4+Shift+9 chain ⛓️ new_attr string my_9️⃣ ⛓️ substitute 🆕 clients.focus.winid set_attr my_9️⃣ 🆕 \
🍂 keybind Mod4+asciicircum use_previous \
🍂 keybind Mod4+grave use_previous \
🍂 keybind Mod4+r remove \
🍂 keybind Mod4+Shift+f floating toggle \
🍂 keybind Mod4+f fullscreen toggle \
🍂 keybind Mod4+Control+Shift+f pseudotile toggle \
🍂 keybind Mod4+BackSpace or 🔙 and 🥨 compare tags.focus.curframe_wcount \!= 2 🥨 cycle_layout +1 max grid horizontal 🔙 cycle_layout +1 max grid \
🍂 mousebind Mod4+Button1 move \
🍂 mousebind Mod4+Button2 zoom \
🍂 mousebind Mod4+Button3 resize \
🍂 keybind Mod4+Next cycle_all --skip-invisible +1 \
🍂 keybind Mod4+Prior cycle_all --skip-invisible -1 \
🍂 keybind Mod1+Tab cycle_all --skip-invisible +1 \
🍂 keybind Mod1+Shift+Tab cycle_all --skip-invisible -1 \
🍂 keybind Mod4+Tab cycle +1 \
🍂 keybind Mod4+Shift+Tab cycle -1 \
🍂 keybind Mod4+Return spawn ${TERMINAL:-xterm} \
🍂 keybind Mod4+F1 spawn $SHELL -c "mupdf =(man -Tpdf \$(apropos . | rofi -dmenu -i -p mansplain | awk '{gsub(/[()]/,\"\"); print \$2\" \"\$1}'))" \
🍂 keybind Mod4+F2 spawn herbstadler \
🍂 keybind Mod4+o spawn abridor.lua \
🍂 keybind Mod4+space spawn rofi -combi-modi window,drun,run -show combi -modi combi \
🍂 keybind Print spawn flameshot gui -p /tmp \
🍂 keybind Mod4+Print spawn flameshot full -c -p /tmp \
🍂 keybind Mod4+u spawn $SHELL -c "xdg-open \$(\\ls -1Qt ${CM_DIR}/clipmenu.5.${USER}/*\ * | xargs awk 1 | grep --only-matching --perl-regexp \"http(s?):\/\/[^ \\\"\(\)\<\>\]]*\" | uniq |rofi -dmenu -i -p 'open URL')" \
🍂 keybind Mod4+i spawn clipmenu -p clipboard \
🍂 keybind Mod4+equal spawn $SHELL -c "notify-send -- \"📋 \$(sort ${CM_DIR}/clipmenu.5.${USER}/line_cache_* | tail -n 1 | cut -d ' ' -f 2- -- -)\"" \
🍂 keybind Mod4+e spawn $SHELL -c "awk 'BEGIN {FS=\"# \"} /;[[:blank:]]fully-qualified/ { sub(\" E[[:digit:]]*.[[:digit:]]* \", \"\\t\", \$2); print \$2 }' $HOME/.local/share/emoji.txt | rofi -dmenu -i -p '¯\_(ツ)_/¯' -no-custom | awk '{printf \$1}' | xsel -ib" \
🍂 keybind Mod4+0 spawn fm0.lua \
🍂 keybind Mod4+t spawn $SHELL -c "$TERMINAL -e tmux new-session -A -s \$(tmux list-clients -F \"#S\" | rofi -dmenu -i -p 'tmux')" \
🍂 keybind Mod4+Escape spawn slock ssh-add -D \
🍂 keybind Mod4+F9 spawn bluetoothctl connect 88:C6:26:F4:8A:90 \
🍂 keybind Mod4+Shift+F9 spawn bluetoothctl disconnect 88:C6:26:F4:8A:90 \
🍂 keybind Mod4+Shift+Return spawn "$TERMINAL" -e tmux \
🍂 keybind Mod4+F12 spawn "$TERMINAL" --class Journalctl -e journalctl -b -f -n 1000 \
🍂 keybind Mod4+F5 cycle_value frame_gap 0 5 10 15 20 \
🍂 keybind Mod4+F6 chain ⛓️ spawn sed -i 's/Qillqaq/Ysgrifennwr/' "$HOME/.config/Code/User/settings.json" ⛓️ spawn sed -i "s/${QI_K#\#}/${YS_K#\#}/;s/${QI_R#\#}/${YS_R#\#}/;s/${QI_G#\#}/${YS_G#\#}/;s/${QI_B#\#}/${YS_B#\#}/;s/${QI_C#\#}/${YS_C#\#}/;s/${QI_M#\#}/${YS_M#\#}/;s/${QI_Y#\#}/${YS_Y#\#}/;s/${QI_W#\#}/${YS_W#\#}/;s/${QI_B_K#\#}/${YS_B_K#\#}/;s/${QI_B_R#\#}/${YS_B_R#\#}/;s/${QI_B_G#\#}/${YS_B_G#\#}/;s/${QI_B_B#\#}/${YS_B_B#\#}/;s/${QI_B_C#\#}/${YS_B_C#\#}/;s/${QI_B_M#\#}/${YS_B_M#\#}/;s/${QI_B_Y#\#}/${YS_B_Y#\#}/;s/${QI_B_W#\#}/${YS_B_W#\#}/;s/${QI_W_80#\#}/${YS_W_80#\#}/" "$HOME/.config/termite/config" "$HOME/.config/rofi/config.rasi" "$HOME/etc/X/.Xdefaults" ⛓️ silent try spawn killall -USR1 termite ⛓️ silent try spawn $SHELL -c "sleep .5 && killall -USR1 termite" \
🍂 keybind Mod4+Shift+F6 chain ⛓️ spawn sed -i 's/Ysgrifennwr/Qillqaq/' "$HOME/.config/Code/User/settings.json" ⛓️ spawn sed -i "s/${YS_K#\#}/${QI_K#\#}/;s/${YS_R#\#}/${QI_R#\#}/;s/${YS_G#\#}/${QI_G#\#}/;s/${YS_B#\#}/${QI_B#\#}/;s/${YS_C#\#}/${QI_C#\#}/;s/${YS_M#\#}/${QI_M#\#}/;s/${YS_Y#\#}/${QI_Y#\#}/;s/${YS_W#\#}/${QI_W#\#}/;s/${YS_B_K#\#}/${QI_B_K#\#}/;s/${YS_B_R#\#}/${QI_B_R#\#}/;s/${YS_B_G#\#}/${QI_B_G#\#}/;s/${YS_B_B#\#}/${QI_B_B#\#}/;s/${YS_B_C#\#}/${QI_B_C#\#}/;s/${YS_B_M#\#}/${QI_B_M#\#}/;s/${YS_B_Y#\#}/${QI_B_Y#\#}/;s/${YS_B_W#\#}/${QI_B_W#\#}/;s/${YS_W_80#\#}/${QI_W_80#\#}/" "$HOME/.config/termite/config" "$HOME/.config/rofi/config.rasi" "$HOME/etc/X/.Xdefaults" ⛓️ silent try spawn killall -USR1 termite ⛓️ silent try spawn $SHELL -c "sleep .5 && killall -USR1 termite" \
🍂 keybind Mod4+F8 and 🥨 cycle_value window_border_active_color $accentcolors 🥨 substitute 🖼️ settings.window_border_active_color chain ⛓️ set frame_bg_active_color 🖼️ ⛓️ emit_hook 🖌️ 🖼️ \
🍂 keybind Mod4+F7 $backdropcmd \
🍂 keybind Mod4+Shift+F7 spawn xsetroot -solid "$QI_W" \
🍂 keybind Mod4+Shift+F6 chain ⛓️ spawn sed -i "s/${YS_K#\#}/${QI_K#\#}/;s/${YS_R#\#}/${QI_R#\#}/;s/${YS_G#\#}/${QI_G#\#}/;s/${YS_B#\#}/${QI_B#\#}/;s/${YS_C#\#}/${QI_C#\#}/;s/${YS_M#\#}/${QI_M#\#}/;s/${YS_Y#\#}/${QI_Y#\#}/;s/${YS_W#\#}/${QI_W#\#}/;s/${YS_B_K#\#}/${QI_B_K#\#}/;s/${YS_B_R#\#}/${QI_B_R#\#}/;s/${YS_B_G#\#}/${QI_B_G#\#}/;s/${YS_B_B#\#}/${QI_B_B#\#}/;s/${YS_B_C#\#}/${QI_B_C#\#}/;s/${YS_B_M#\#}/${QI_B_M#\#}/;s/${YS_B_Y#\#}/${QI_B_Y#\#}/;s/${YS_B_W#\#}/${QI_B_W#\#}/;s/${YS_W_80#\#}/${QI_W_80#\#}/" "$HOME/.config/alacritty/alacritty.yml" "$HOME/.config/rofi/config.rasi" "$HOME/etc/X/.Xdefaults" ⛓️ spawn sed -i 's/Ysgrifennwr/Qillqaq/' "$HOME/.config/Code/User/settings.json" \
🍂 keybind Mod4+apostrophe and 🥨 toggle always_show_frame 1 🥨 spawn $SHELL -c 'sleep 1 && herbstclient toggle always_show_frame' \
🍂 keybind Mod4+Shift+apostrophe toggle always_show_frame \
🍂 keybind Mod4+p spawn $HOME/.config/herbstluftwm/herbstschau.sh \
🍂 keybind Mod4+m or 🖕 and 🥨 compare monitors.focus.lock_tag  = false 🥨 lock_tag "" 🥨 substitute 🖥️ monitors.focus.index emit_hook 🔒 🖥️ 🖕 and 🥨 unlock_tag "" 🥨 substitute 💻 monitors.focus.index emit_hook 🔓 💻 \
🍂 keybind Mod4+comma focus_monitor -l \
🍂 keybind Mod4+period focus_monitor -r \
🍂 keybind Mod4+Shift+comma shift_to_monitor -l \
🍂 keybind Mod4+Shift+period shift_to_monitor -r \
🍂 keybind Mod4+Control+Shift+q quit \
🍂 keybind Mod4+Shift+q reload \
🍂 keybind Mod4+F4 close \
🍂 keybind Mod4+KP_Insert $mutecmd \
🍂 keybind Mod4+KP_Subtract $lowervolumecmd \
🍂 keybind Mod4+KP_Add $raisevolumecmd \
🍂 keybind Mod4+KP_End spawn $strawberryplaycmd \
🍂 keybind Mod4+KP_Multiply spawn $strawberrynextcmd \
🍂 keybind Mod4+KP_Divide spawn $strawberryprevcmd \
$localbinds \
🍂 rule focus=on \
🍂 rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on \
🍂 rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on \
🍂 rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off \
🍂 rule class=SshAskpass pseudotile=on \
🍂 rule class=mpv instance=gl index=10 focus=on switchtag=on \
🍂 rule title='Picture in picture' index=10 focus=off \
🍂 rule instance=FM0 tag='$' focus=off switchtag=off \
🍂 rule instance=Journalctl tag='#' focus=off switchtag=off \
🍂 rule once class=Google-chrome index=0 focus=on switchtag=on \
🍂 rule once class=Firefox instance=Navigator index=0 focus=on switchtag=on \
🍂 rule once class=Code index=0 focus=on switchtag=on \
🍂 rule class=discord tag='^' \
🍂 rule class=TelegramDesktop tag='^' \
🍂 rule class=Steam tag='^' \
🍂 rule instance=Weechat tag='^' \
🍂 rule class=presenter title=sent instance=sent fullscreen=true \
🍂 rule class=strawberry tag='$' focus=on switchtag=off \
🍂 rule class=Spotify tag='$' focus=on switchtag=off \
🍂 rule title~'MuPDF: .*' index=0 focus=on switchtag=on \
🍂 detect_monitors --no-disjoin \
🍂 unlock &


~/.config/herbstluftwm/restartpanel.sh

# TODO find running journalctl instance
# herbstclient keybind Mod4+n chain ⛓️ keybind h and 🥨 shift left 🥨 keyunbind Escape 🥨 keyunbind h ⛓️ keybind Escape and 🥨 keyunbind Escape 🥨 keyunbind h
# IDEA: store layouts in z/y
# 🍂 keybind Mod4+Control+1 load '(clients max:0)' \
# 🍂 keybind Mod4+Control+2 load '(split horizontal:0.626100:0 (clients max:1) (split vertical:0.395300:1 (clients max:0) (clients max:0)))' \
# 🍂 keybind Mod4+Control+3 load '(clients grid:0)' \
# 🍂 keybind Mod4+Control+4 load '(clients max:0)' \
# 🍂 keybind Mod4+Control+5 load '(split horizontal:0.550000:0 (clients max:0) (clients max:0))' \
# 🍂 substitute 🏷️ tags.focus.name substitute 🖥️ monitors.focus.index emit_hook tag_changed 🏷️ 🖥️
# 🍂 substitute TAG tags.focus.name substitute MONITOR monitors.focus.index emit_hook tag_changed TAG MONITOR
# 🍂 set tree_style "-| |\`--." \
