#!/usr/bin/zsh

herbstclient emit_hook reload

herbstclient set frame_gap 4
herbstclient set frame_padding 0
herbstclient set window_gap 0
herbstclient set snap_distance 10
herbstclient set snap_gap 0
herbstclient set mouse_recenter_gap 0
herbstclient set frame_border_active_color '#1e1e1e'
herbstclient set frame_border_normal_color '#1e1e1e'
herbstclient set frame_border_inner_color '#1e1e1e'
herbstclient set frame_bg_active_color '#e3c472'
herbstclient set frame_bg_normal_color '#424242'
herbstclient set frame_bg_transparent 1
herbstclient set frame_transparent_width 5
herbstclient set frame_border_width 1
herbstclient set frame_border_inner_width 0
herbstclient set focus_crosses_monitor_boundaries 1
herbstclient set raise_on_focus 0
herbstclient set raise_on_focus_temporarily 0
herbstclient set raise_on_click 1
herbstclient set window_border_width 3
herbstclient set window_border_inner_width 1
herbstclient set window_border_active_color '#30c798'
herbstclient set window_border_normal_color '#424242'
herbstclient set window_border_urgent_color '#e32791'
herbstclient set window_border_inner_color '#1e1e1e'
herbstclient set always_show_frame 0
herbstclient set frame_normal_opacity 100
herbstclient set frame_active_opacity 100
herbstclient set default_frame_layout 3
herbstclient set default_direction_external_only 0 ### TODO
herbstclient set gapless_grid 1
herbstclient set smart_frame_surroundings 1
herbstclient set smart_window_surroundings 0
herbstclient set focus_follows_mouse 0
herbstclient set focus_stealing_prevention 0
herbstclient set swap_monitors_to_get_tag 1
herbstclient set auto_detect_monitors 0 ### TODO
herbstclient set tree_style '├│ ├└──┬'
herbstclient set update_dragged_clients 1

herbstclient keyunbind --all

herbstclient keybind Mod4-Shift-q quit
herbstclient keybind Mod4-Shift-r reload
herbstclient keybind Mod4-q close

TERMINALCMD=(alacritty --live-config-reload)
MAX_BRIGHTNESS=$(</sys/class/backlight/intel_backlight/max_brightness)

herbstclient keybind Mod4-Return spawn $TERMINALCMD
herbstclient keybind Mod4-p spawn rofi -show run
herbstclient keybind Mod4-Shift-p spawn rofi -show drun
herbstclient keybind Mod4-l spawn rofi -show window
herbstclient keybind Mod4+e spawn $SHELL -c "rofi -dmenu -i -p Emoji -input $HOME/.local/share/emoji.txt | awk '{printf \$1}' | xsel -ib"
herbstclient keybind Mod4+F1 spawn $SHELL -c "mupdf-gl =(man -Tpdf \$(apropos . | rofi -dmenu -i -p mansplain | awk '{gsub(/[()]/,\"\"); print \$2\" \"\$1}'))"
herbstclient keybind XF86AudioRaiseVolume spawn amixer sset Master 5%+ unmute
herbstclient keybind XF86AudioLowerVolume spawn amixer sset Master 5%- unmute
herbstclient keybind XF86AudioMute spawn amixer sset Master mute
herbstclient keybind XF86MonBrightnessDown spawn $SHELL -c "brightness=\$(</sys/class/backlight/intel_backlight/brightness); new_brightness=\$((-$MAX_BRIGHTNESS/10+\$brightness)); actual_brightness=\$((\$new_brightness > 0 ? \$new_brightness : 0)); echo \$actual_brightness > /sys/class/backlight/intel_backlight/brightness"
# TODO alter new brightness like: xsetroot -name \"brightness: \$((100 * \$actual_brightness / $MAX_BRIGHTNESS)) %\""
herbstclient keybind XF86MonBrightnessUp spawn $SHELL -c "brightness=\$(</sys/class/backlight/intel_backlight/brightness) ; new_brightness=\$(($MAX_BRIGHTNESS/10+\$brightness)) ; actual_brightness=\$((\$new_brightness < $MAX_BRIGHTNESS ? \$new_brightness : $MAX_BRIGHTNESS)) ; echo \$actual_brightness > /sys/class/backlight/intel_backlight/brightness"
herbstclient keybind Mod4+Escape and , spawn ssh-add -D , spawn i3lock -c \#000000
herbstclient keybind Mod4+o spawn $HOME/etc/suckless/abridor/abridor.lua
# TODO find running journalctl instance
herbstclient keybind Mod4+F12 spawn $TERMINALCMD --class journalctl -T journalctl -e journalctl -b -f -n 1000
# TODO: bind weechat like "$TERMINALCMD --class weechat -T weechat -- weechat"
herbstclient keybind Mod4+0 spawn $HOME/etc/suckless/fm0/fm0.lua
herbstclient keybind Mod4+F9 spawn bluetoothctl connect 88:C6:26:F4:8A:90
herbstclient keybind Mod4+Shift+F9 spawn bluetoothctl disconnect 88:C6:26:F4:8A:90
herbstclient keybind XF86AudioPlay spawn strawberry --play-pause
herbstclient keybind XF86AudioNext spawn strawberry --next
herbstclient keybind XF86AudioPrev spawn strawberry --restart-or-previous
herbstclient keybind Print spawn flameshot gui -p /tmp
herbstclient keybind Mod4+Print spawn flameshot screen -c -p /tmp
herbstclient keybind Mod4+i spawn clipmenu -p Clipboard
herbstclient keybind Mod4+u spawn $SHELL -c "xdg-open \$(\\ls -1Qt ${CM_DIR}/clipmenu.5.${USER}/*\ * | xargs awk 1 | grep --only-matching --perl-regexp \"http(s?):\/\/[^ \\\"\(\)\<\>\]]*\" | uniq |rofi -dmenu -i -p 'open URL')"
herbstclient keybind Mod4+t spawn $SHELL -c "$TERMINALCMD -e tmux new-session -A -s \$(tmux list-clients -F \"#S\" | rofi -dmenu -i -p 'Attach to tmux session:')"
herbstclient keybind Mod4+Shift+F6 spawn xsetroot -solid '#1e1e1e'
herbstclient keybind Mod4+F6 spawn $SHELL -c "xsetroot -bitmap $HOME/etc/suckless/backdrops/\`\\ls $HOME/etc/suckless/backdrops | shuf -n 1 | tr -d '\\n' | tee -a /tmp/wallpaper\` \`printf -- \" -fg #%06x -bg #%06x\\n\" \$(shuf -i0-16777215 -n2) | tee -a /tmp/wallpaper\`"
herbstclient keybind Mod4+numbersign toggle always_show_frame
herbstclient keybind Mod4+7 or , and . compare settings.window_border_active_color = '#30c798' . and \; set window_border_active_color '#e3c472' \; set frame_bg_active_color '#e3c472' , and . compare settings.window_border_active_color = '#e3c472' . and \; set window_border_active_color '#81d8d0' \; set frame_bg_active_color '#81d8d0' , and . compare settings.window_border_active_color = '#81d8d0' . and \; set window_border_active_color '#6769e6' \; set frame_bg_active_color '#6769e6' , and . compare settings.window_border_active_color = '#6769e6' . and \; set window_border_active_color '#e59fdf' \; set frame_bg_active_color '#e59fdf' , and \; set window_border_active_color '#30c798' \; set frame_bg_active_color '#30c798'
herbstclient keybind Mod4+F6 chain . spawn sed -i "s/${QI_K#\#}/${YS_K#\#}/;s/${QI_R#\#}/${YS_R#\#}/;s/${QI_G#\#}/${YS_G#\#}/;s/${QI_B#\#}/${YS_B#\#}/;s/${QI_C#\#}/${YS_C#\#}/;s/${QI_M#\#}/${YS_M#\#}/;s/${QI_Y#\#}/${YS_Y#\#}/;s/${QI_W#\#}/${YS_W#\#}/;s/${QI_B_K#\#}/${YS_B_K#\#}/;s/${QI_B_R#\#}/${YS_B_R#\#}/;s/${QI_B_G#\#}/${YS_B_G#\#}/;s/${QI_B_B#\#}/${YS_B_B#\#}/;s/${QI_B_C#\#}/${YS_B_C#\#}/;s/${QI_B_M#\#}/${YS_B_M#\#}/;s/${QI_B_Y#\#}/${YS_B_Y#\#}/;s/${QI_B_W#\#}/${YS_B_W#\#}/" $HOME/.config/alacritty/alacritty.yml . spawn sed -i 's/Qillqaq/Ysgrifennwr/' "$HOME/.config/Code/User/settings.json"
herbstclient keybind Mod4+Shift+F6 chain . spawn sed -i "s/${YS_K#\#}/${QI_K#\#}/;s/${YS_R#\#}/${QI_R#\#}/;s/${YS_G#\#}/${QI_G#\#}/;s/${YS_B#\#}/${QI_B#\#}/;s/${YS_C#\#}/${QI_C#\#}/;s/${YS_M#\#}/${QI_M#\#}/;s/${YS_Y#\#}/${QI_Y#\#}/;s/${YS_W#\#}/${QI_W#\#}/;s/${YS_B_K#\#}/${QI_B_K#\#}/;s/${YS_B_R#\#}/${QI_B_R#\#}/;s/${YS_B_G#\#}/${QI_B_G#\#}/;s/${YS_B_B#\#}/${QI_B_B#\#}/;s/${YS_B_C#\#}/${QI_B_C#\#}/;s/${YS_B_M#\#}/${QI_B_M#\#}/;s/${YS_B_Y#\#}/${QI_B_Y#\#}/;s/${YS_B_W#\#}/${QI_B_W#\#}/" $HOME/.config/alacritty/alacritty.yml . spawn sed -i 's/Ysgrifennwr/Qillqaq/' "$HOME/.config/Code/User/settings.json"

# TODO xsetroot -name "$(cat ${CM_DIR}/clipmenu.5.${USER}/line_cache_* | sort | tail --lines=1 | cut -d ' ' -f 2- -- -)"

# moving clients
herbstclient keybind Mod4-Left  shift left
herbstclient keybind Mod4-Down  shift down
herbstclient keybind Mod4-Up    shift up
herbstclient keybind Mod4-Right shift right
herbstclient keybind Mod4-a     shift left
herbstclient keybind Mod4-s     shift down
herbstclient keybind Mod4-w     shift up
herbstclient keybind Mod4-d     shift right

# splitting frames
# create an empty frame at the specified direction
herbstclient keybind Mod4-b       split   bottom  0.5
herbstclient keybind Mod4-r       split   right   0.5
# let the current frame explode into subframes
herbstclient keybind Mod4-Control-space split explode

# resizing frames
resizestep=0.03
herbstclient keybind Mod4-Shift-a       resize left +$resizestep
herbstclient keybind Mod4-Shift-s       resize down +$resizestep
herbstclient keybind Mod4-Shift-w       resize up +$resizestep
herbstclient keybind Mod4-Shift-d       resize right +$resizestep
herbstclient keybind Mod4-Shift-Left    resize left +$resizestep
herbstclient keybind Mod4-Shift-Down    resize down +$resizestep
herbstclient keybind Mod4-Shift-Up      resize up +$resizestep
herbstclient keybind Mod4-Shift-Right   resize right +$resizestep

herbstclient rename default '!'
herbstclient add '!'
herbstclient load '!' '(clients max:0)'
herbstclient add '@'
herbstclient load '@' '(split horizontal:0.638200:0 (clients max:1) (split vertical:0.380500:1 (clients max:0) (clients max:0)))'
herbstclient add '#'
herbstclient load '#' '(clients grid:0)'
herbstclient add '$'
herbstclient load '$' '(clients max:0)'
herbstclient add '%'
herbstclient load '%' '(split horizontal:0.550000:0 (clients max:0) (clients max:0))'
herbstclient add '^'
herbstclient keybind Mod4-1 use_index 0
herbstclient keybind Mod4-2 use_index 1
herbstclient keybind Mod4-3 use_index 2
herbstclient keybind Mod4-4 use_index 3
herbstclient keybind Mod4-5 use_index 4
herbstclient keybind Mod4-6 use_index 5
herbstclient keybind Mod4-Shift-1 move_index 0
herbstclient keybind Mod4-Shift-2 move_index 1
herbstclient keybind Mod4-Shift-3 move_index 2
herbstclient keybind Mod4-Shift-4 move_index 3
herbstclient keybind Mod4-Shift-5 move_index 4
herbstclient keybind Mod4-Shift-6 move_index 5
herbstclient keybind Mod4-Control-1 load '(clients max:0)'
herbstclient keybind Mod4-Control-2 load '(split horizontal:0.638200:0 (clients max:1) (split vertical:0.380500:1 (clients max:0) (clients max:0)))'
herbstclient keybind Mod4-Control-3 load '(clients grid:0)'
herbstclient keybind Mod4-Control-4 load '(clients max:0)'
herbstclient keybind Mod4-Control-5 load '(split horizontal:0.550000:0 (clients max:0) (clients max:0))'

# cycle through tags
herbstclient keybind Mod4-period use_index +1 --skip-visible
herbstclient keybind Mod4-comma  use_index -1 --skip-visible

# layouting
herbstclient keybind Mod4-Shift-c remove
herbstclient keybind Mod4-x split explode
herbstclient keybind Mod4-f floating toggle
herbstclient keybind Mod4-m fullscreen toggle
herbstclient keybind Mod4-v pseudotile toggle

herbstclient keybind Mod4-space or , and . compare tags.focus.curframe_wcount = 2 . cycle_layout +1 max grid max horizontal vertical , cycle_layout +1 max grid horizontal

# mouse
herbstclient mouseunbind --all
herbstclient mousebind Mod4-Button1 move
herbstclient mousebind Mod4-Button2 zoom
herbstclient mousebind Mod4-Button3 resize

# focus
herbstclient keybind Mod4-BackSpace cycle_monitor
herbstclient keybind Mod4-j         cycle_all --skip-invisible +1
herbstclient keybind Mod4-k         cycle_all --skip-invisible -1
herbstclient keybind Mod4-Tab       cycle +1
herbstclient keybind Mod4-Shift-Tab cycle -1

# rules
herbstclient unrule -F
herbstclient rule focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule class=mpv instance=gl tag='@' index='10' focus=on switchtag=on
herbstclient rule class=Alacritty instance=FM0 tag='#' focus=off switchtag=off
herbstclient rule once class=Google-chrome tag='@' index='00' focus=on switchtag=on
herbstclient rule once class=Code tag='@' index='00' focus=on switchtag=on
herbstclient rule class=discord tag='^'
herbstclient rule class=TelegramDesktop tag='^'
herbstclient rule class=Steam tag='^'
herbstclient rule class=presenter title=sent instance=sent fullscreen=true
herbstclient rule class=strawberry tag='$' focus=on switchtag=off

# unlock, just to be sure
herbstclient unlock

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# herbstclient detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[[ -x "$panel" ]] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
