-- This file has been generated by notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["type"] = "WGroupWS",
                ["switchto"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitSplit",
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["name"] = "Tiling Frame<1>",
                                        ["mode"] = 1.0,
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["br"] = {
                                    ["type"] = "WSplitSplit",
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["type"] = "WFrame",
                                            ["saved_h"] = 384.0,
                                            ["managed"] = {
                                            },
                                            ["name"] = "Tiling Frame<3>",
                                            ["mode"] = 1.0,
                                            ["saved_y"] = 0.0,
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                            },
                                            ["name"] = "Tiling Frame<4>",
                                            ["mode"] = 1.0,
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["brs"] = 455.0,
                                    ["tls"] = 288.0,
                                    ["dir"] = "vertical",
                                },
                                ["brs"] = 454.0,
                                ["tls"] = 912.0,
                                ["dir"] = "horizontal",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 25.0,
                            ["tls"] = 743.0,
                            ["dir"] = "vertical",
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                        },
                    },
                },
                ["name"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                },
            },
            [2] = {
                ["level"] = 0.0,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["name"] = "Tiling Frame",
                                    ["mode"] = 1.0,
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 25.0,
                            ["tls"] = 743.0,
                            ["dir"] = "vertical",
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<1>",
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                        },
                    },
                },
                ["name"] = "WGroupWS<1>",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                },
            },
            [3] = {
                ["level"] = 0.0,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["name"] = "Tiling Frame<2>",
                                    ["mode"] = 1.0,
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 25.0,
                            ["tls"] = 743.0,
                            ["dir"] = "vertical",
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<2>",
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                        },
                    },
                },
                ["name"] = "WGroupWS<2>",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                },
            },
            [4] = {
                ["level"] = 0.0,
                ["type"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<3>",
                                    ["mode"] = 1.0,
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 25.0,
                            ["tls"] = 743.0,
                            ["dir"] = "vertical",
                        },
                        ["type"] = "WTiling",
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<3>",
                        ["level"] = 0.0,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 768.0,
                            ["w"] = 1366.0,
                            ["x"] = 0.0,
                        },
                    },
                },
                ["name"] = "WGroupWS<3>",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                },
            },
            [5] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["level"] = 1.0,
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 768.0,
                    ["w"] = 1366.0,
                    ["x"] = 0.0,
                },
                ["hidden"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                        ["level"] = 1024.0,
                        ["managed"] = {
                        },
                        ["name"] = "*scratchpad*",
                        ["mode"] = 0.0,
                        ["geom"] = {
                            ["y"] = 144.0,
                            ["h"] = 469.0,
                            ["w"] = 632.0,
                            ["x"] = 363.0,
                        },
                    },
                },
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

