-- This file has been generated by notion. Do not edit.
return {
    [1] = {
        ["name"] = "WScreen<1>",
        ["managed"] = {
            [1] = {
                ["initial_outputs"] = {
                    [1] = "HDMI-2",
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1.0,
                                        ["name"] = "Tiling Frame<1>",
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1.0,
                                        ["name"] = "Tiling Frame<2>",
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["tls"] = 518.0,
                                ["brs"] = 562.0,
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1.0,
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 5.0,
                                                    ["level"] = 0.0,
                                                    ["windowid"] = 6291518.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 1047.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                        ["h"] = 1054.0,
                                                    },
                                                },
                                            },
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW<3>",
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["w"] = 1047.0,
                                                ["x"] = 2.0,
                                                ["y"] = 24.0,
                                                ["h"] = 1054.0,
                                            },
                                        },
                                        [2] = {
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 6.0,
                                                    ["level"] = 0.0,
                                                    ["windowid"] = 35651589.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 1040.0,
                                                        ["x"] = 3.0,
                                                        ["y"] = 5.0,
                                                        ["h"] = 1044.0,
                                                    },
                                                },
                                            },
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW<5>",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["w"] = 1047.0,
                                                ["x"] = 2.0,
                                                ["y"] = 24.0,
                                                ["h"] = 1054.0,
                                            },
                                        },
                                    },
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1051.0,
                            ["brs"] = 869.0,
                        },
                        ["level"] = 0.0,
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                            ["h"] = 1080.0,
                        },
                    },
                },
                ["switchto"] = true,
                ["level"] = 0.0,
                ["name"] = "WGroupWS<1>",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [2] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [3] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<2>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<2>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [4] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<3>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<3>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [5] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<4>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<4>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [6] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<5>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<5>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [7] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<6>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<6>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
            [8] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<7>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<7>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 800.0,
                            ["x"] = 560.0,
                            ["y"] = 240.0,
                            ["h"] = 600.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                },
            },
        },
        ["type"] = "WScreen",
    },
    [0] = {
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["initial_outputs"] = {
                    [1] = "HDMI-1",
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["br"] = {
                                ["dir"] = "vertical",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1.0,
                                        ["name"] = "Tiling Frame<3>",
                                        ["managed"] = {
                                            [1] = {
                                                ["sizepolicy"] = "full",
                                                ["switchto"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["sizepolicy"] = "full",
                                                        ["type"] = "WClientWin",
                                                        ["checkcode"] = 4.0,
                                                        ["level"] = 0.0,
                                                        ["windowid"] = 25165829.0,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 806.0,
                                                            ["x"] = 2.0,
                                                            ["y"] = 0.0,
                                                            ["h"] = 1154.0,
                                                        },
                                                    },
                                                },
                                                ["level"] = 0.0,
                                                ["name"] = "WGroupCW<4>",
                                                ["type"] = "WGroupCW",
                                                ["geom"] = {
                                                    ["w"] = 810.0,
                                                    ["x"] = 2.0,
                                                    ["y"] = 24.0,
                                                    ["h"] = 1155.0,
                                                },
                                            },
                                        },
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["tls"] = 1181.0,
                                ["brs"] = 19.0,
                            },
                            ["tl"] = {
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 1.0,
                                                    ["level"] = 0.0,
                                                    ["windowid"] = 27262981.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 1094.0,
                                                        ["x"] = 4.0,
                                                        ["y"] = 10.0,
                                                        ["h"] = 1154.0,
                                                    },
                                                },
                                            },
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW<2>",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["w"] = 1102.0,
                                                ["x"] = 2.0,
                                                ["y"] = 24.0,
                                                ["h"] = 1174.0,
                                            },
                                        },
                                        [2] = {
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 2.0,
                                                    ["level"] = 0.0,
                                                    ["windowid"] = 6291461.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 1102.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                        ["h"] = 1174.0,
                                                    },
                                                },
                                            },
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW",
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["w"] = 1102.0,
                                                ["x"] = 2.0,
                                                ["y"] = 24.0,
                                                ["h"] = 1174.0,
                                            },
                                        },
                                        [3] = {
                                            ["sizepolicy"] = "full",
                                            ["switchto"] = true,
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["checkcode"] = 3.0,
                                                    ["level"] = 0.0,
                                                    ["windowid"] = 16777223.0,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["w"] = 1102.0,
                                                        ["x"] = 0.0,
                                                        ["y"] = 0.0,
                                                        ["h"] = 1174.0,
                                                    },
                                                },
                                            },
                                            ["level"] = 0.0,
                                            ["name"] = "WGroupCW<1>",
                                            ["type"] = "WGroupCW",
                                            ["geom"] = {
                                                ["w"] = 1102.0,
                                                ["x"] = 2.0,
                                                ["y"] = 24.0,
                                                ["h"] = 1174.0,
                                            },
                                        },
                                    },
                                    ["name"] = "Tiling Frame",
                                    ["saved_x"] = 0.0,
                                    ["saved_w"] = 1011.0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1106.0,
                            ["brs"] = 814.0,
                        },
                        ["level"] = 0.0,
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                            ["y"] = 0.0,
                            ["h"] = 1200.0,
                        },
                    },
                },
                ["switchto"] = true,
                ["level"] = 0.0,
                ["name"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1200.0,
                },
            },
            [2] = {
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*<1>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["level"] = 1024.0,
                        ["name"] = "*scratchpad*<1>",
                        ["managed"] = {
                        },
                        ["geom"] = {
                            ["w"] = 792.0,
                            ["x"] = 560.0,
                            ["y"] = 300.0,
                            ["h"] = 581.0,
                        },
                    },
                },
                ["level"] = 1.0,
                ["hidden"] = true,
                ["geom"] = {
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                    ["y"] = 0.0,
                    ["h"] = 1200.0,
                },
            },
        },
        ["type"] = "WScreen",
    },
}

