#!/bin/zsh

resolution=$(xrandr --nograb --current | awk -F 'connected |\\+|\\(' '/ connected/ && $2 {printf $2, ", "}' | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')

files=( $HOME/var/wallpapers/**/*$resolution.png )
for i in $files
do
	thumbname="$1/$(basename $i)"
	[ -f "$thumbname" ] || convert -quality 0 -sample 64x64 "$i" "$thumbname"
	echo AddToMenu WallpaperMenu "%'$thumbname'%'$(basename $i)'" SetBG "'$i'"
done
